### ISSUE TITLE
Sun Position 

### ISSUE THREAD

**Issue by tamirlance** [NREL/SolTrace#19]
The LK script language should support changing sun position types.  Just setting the latitude, day and hour doesn't do anything if the radio button in the GUI is set to global coordinates (which is selected by default when launching the program).

**Comment by mjwagner2** [comment]
@tamirlance The script language call for changing sun position supports setting the sun position type using the ```'useldh'=1``` option in the ```sunopt( ... )``` call. If you don't have this flag set to '1', then settings for day, hour, and latitude are ignored. The correct LK syntax might be something like:

```
sunoptions = { 
	'ptsrc'=0,
	'shape'='p',
	'x'=0,
	'sigma'=0,
	'halfwidth'=4.65,
	'y'=0,
	'z'=100,
	'useldh'=1,
	'lat'=39.5,
	'day'=180,
	'hour'=15
	};
	
sunopt(sunoptions);

trace();
```

**Comment by tamirlance** [comment]
Ah yes - I copied my code from a previous version of Soltrace in which that didn't exist I don't think.  Thanks for pointing it out
