### ISSUE TITLE
Can't seem to find soltrace.exe

### ISSUE THREAD

**Issue by Zane1996** [NREL/SolTrace#23]
The final step is to open soltrace.exe in the deploy folder, but I can't seem to find it. I have even typed in soltrace.exe in the search bar, but still found nothing. Could I have made a mistake during the setup and builds?

**Comment by mjwagner2** [comment]
Hi @Zane1996, if everything is built correctly, the executable should be in the folder /app/deploy/<platform>/ -- for example: /soltrace/app/deploy/x64/soltrace.exe. If it doesn't appear there, the build was likely not successful. Could you attach the output from your build log? That may give some clues.
